# Pipeline
iterations: 20000
densify_from: 2000
densify_until: 11000
densify_factor: 1.15
contrast_fraction: 0.5
loss_type: l2
debug: False
viewer: False
save_volume: False
interpolation_start: 7500
interp_ramp: False
interp_sigma_scale: 0.55
interp_sigma_v: 0.2
redundancy_threshold: 0.01
redundancy_cap: 0.05
rays_per_batch: 2000000

# Model
init_points: 16000
final_points: 128000
activation_scale: 1.0
init_scale: 1.05
init_type: random
device: cuda

# Optimization
points_lr_init: 2e-4
points_lr_final: 1e-6
density_lr_init: 1e-1
density_lr_final: 5e-3
freeze_points: 17000
tv_weight: 1e-4
tv_start: 8000
tv_epsilon: 1e-4
tv_area_weighted: False
gradient_start: -1
#
# Dataset
dataset: r2_gaussian
data_path: /mnt/hdd/r2_data/synthetic_dataset/cone_ntrain_75_angle_360/0_chest_cone
